{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "avalanche.fullname" . }}
  labels:
{{ include "avalanche-helm.labels" . | indent 4 }}
spec:
  endpoints:
  - interval: 30s
    port: metrics
    path: /metrics
    metricRelabelings:
      sourceLabels: ['namespace', 'job']
      separator: "/"
      targetLabel: 'instance'
  selector:
    matchLabels:
      prometheus-scrape-enabled: "true"
{{ include "avalanche.labels" . | indent 6 }}
{{- end }}
